### ISSUE TITLE
Move to yiisoft/translator

### ISSUE THREAD

**Issue by vjik** [yiisoft/translator-formatter-simple#2]
Maybe simple implementations of translator interfaces (without dependencies) place in `yiisoft/translator` itself, not separately?

**Comment by darkdef** [comment]
Now simple formatter is really a simply, but when will be a complex? Today it's may be a good idea. After this package may will be split(excluded formatter)

**Comment by samdark** [comment]
It should not become any more complex but I wonder how to ensure automatic-configuration to use intl one when both packages are required.

**Comment by darkdef** [comment]
When move this package to yiisoft/translator - we will have problem with usaging intl-package after install yiisoft/translator-formatter-intl.
Now formatters automatically configuring with `composer require` and this be simple
