### ISSUE TITLE
Close package and move code to `yiisoft/translator`

### ISSUE THREAD

**Issue by vjik** [yiisoft/translator-formatter-simple#25]
Package has no dependencies other than translator. We can move this formatter to `yiisoft/translator`.

In case, when use `yiisoft/translator` (for example idea with using in validator), we require one package only instead of two.

**Comment by samdark** [comment]
@darkdef what do you think?

**Comment by darkdef** [comment]
I agree

**Comment by DAGpro** [comment]
Done https://github.com/yiisoft/translator/pull/62

**Comment by arogachev** [comment]
Now need to wait for `yiisoft/translator` release.

**Comment by samdark** [comment]
I'll handle this one.
